# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bf40320a82ebc1fcebd31ef22e31baa690c56baab440513c4fb145800ece4a43c8b33e15f5fc649e537da6b2b7891118db1ff35029813a41171b2b61688676f

test:
  secret_key_base: 3c36c9e551fb8f0bdb87a511ba7ae8538b82d65b49575a17921fb5e30ae3d1936cac9c43eef9e808ad638f4403250bec9b062bff8046934f8c0ee9d70b9f52c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
